apiVersion: v1
data:
    host_key: ENC[AES256_GCM,data:iKXq6322wzhwo6AieKdEfEzxM5lkD2AJebgRvmRWPEURSGkJGf43HEVhmxtAp5jv9fDLOf47aBzduuaVx9XRlTvHeTM4IusSo3v9Yqxg7coUdt3XHBJNe9FPmoscD+iCUbiS2NF+EuqP5OLEUI6DeJUywNS5FtHmMXKnTJpL7bbvZkRuVwE2Ewsq0cfr8CkWy5YblUYKAck/Mcn0uO5b72jnPFLDTtmZdB5NeHQHt0HFUnMGAyBTFNZf2AAOQt/JeVCE9ZDGFgLe1KdD2T+hr4dXEOfshPVZDDw0n0/TibQtd+BdqU6yBIQJrlYdwl/rfIXML3eidU/uiog049PRMH/j92OHUOZrxMEGE9y1xAr+c6uZO61IS8zIjPFzV/e6B7XZBoqZMvYNPwoGcaFLl0w6u1H6iroPcreD7dZ5qf79SL2ooJc09mp0IM294nvuFcLCiMWQZftZqL5bfd5vbUeewhQbp1Pq7EY4KlZXga8jWnLPm5rcqHSqns9mdQNmIEDhtk4iMEd6wv1hrh8p3A9n6KglHfbEnQDhXqkzpkXCHj41sq9Z9VFp5u4xJgkgGZGOnAwLok3d/mTCPVqlOhOgEExpHh4SvIY5zkmzSpFBkMQ5F7jrPgRBqp5LYxCv32b/AD7qPZ29lJQncO610loA6MzOc9AVdHWZjlAM6I1MKLeZIZdtTG+wfAKzTHRTTbv81w==,iv:GwUer5UDdZOZ3KymTNrSp+ta2zcSnaEWZsXOG8fGn9M=,tag:PxI676T2hMRg83jswnRMhA==,type:str]
    host_key.pub: ENC[AES256_GCM,data:gI57eF851bWVSTQZ2thjhrPlk+Y3gm5WsH1tX7D+EuajfzfLV04Z55cLneudLQQ/G5Fchk4fpuSJ9mp3fs92suc0hbpz42MPFa5Oru5MdzHgAG+283I3Ca+ssw7RNQeEr0VMxVbIelUNe5NXqmoa8RzHpcfPnW5Y2u9FB7Wo7vM=,iv:1j9ciPqN6DIodNS3F2yHUbGoPG3ggpC52OgC9epIFdY=,tag:4eku8iTuc8ZO1WcmbCRrYw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: portfolio-ssh-keys
    namespace: app-portfolio
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSUZVcXdqTjdIeTVtbDJK
            Qlg0MWdRWWpmc2hpdDdYc1ZGTFhocnJXejIwClJOa1hkbklrNHJwQk1SS0VGbEdw
            eUQzZFMxRG9BdEJBSU91ZTl6VFhPVGsKLS0tIHVrRWdVUUFYNm5pWUsrNkNuclRa
            UERiRVhoK3VDMDhCSHgwMW5hWFVjZ00KscSYeaDL7hU5+OPn9jGrxy9q/8X6YLgn
            jGXWi83WaeKlL693PNPlhN8GhmmZsGjR36iXd0ayomaun733fnUqpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1shky7qvjsjetam7p0wyc2urxtaszvd6970y9dlzzjcakryy8xapqd5pupw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T20:20:54Z"
    mac: ENC[AES256_GCM,data:abv+3Fy8tfeW91MF/fyRm3g5JyKXytXvVIb2mHk2uNtjAny5RGUiZCy5/kQkRzW1vLeBVIRZ3+c2b/FfkLBXNnpF+SzHMly+sUOvovWGn4T69mOiz1bZaab4Ph5VquSjFOQpnRi7zfcNPIh+2Hm9GUUBBRAQsW05u7CFOkiTXJ0=,iv:Uaq71RXEF+Ah+xYE5Wo9LVBfI8ZvQ72FSy+fBU97GJA=,tag:WvQGR5JRGWG9JkHCoSVjEQ==,type:str]
    version: 3.13.3
